name: build

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  gdlint:
    name: Lint
    runs-on: ubuntu-latest

    env:
      PROBLEMS_THRESHOLD: 0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'gdtoolkit==4.*'

      - name: Lint code
        run: |
          gdlint $(find . -name "*.gd" -not -path "./addons/*") > gdlint_output.txt 2>&1 || true
          cat gdlint_output.txt

      - name: Check linter results
        run: |
          PROBLEMS=$(grep -o 'Failure: \K\d+' gdlint_output.txt || echo "0")
          echo "Problems found: $PROBLEMS"
          echo "Threshold is: $PROBLEMS_THRESHOLD"
          if [ "$PROBLEMS" -gt "$PROBLEMS_THRESHOLD" ]; then
            echo "Quality check failed."
            exit 1
          fi
